name = "seminar"
compatibility_date = "2026-02-26"
pages_build_output_dir = "apps/web/dist"

[[d1_databases]]
binding = "DB"
database_name = "seminar-leads"
database_id = "1aebef71-1a70-4a3f-8714-aa1fe9091168"
preview_database_id = "49a55d3c-96d7-47f3-bacb-af6abec37fa1"
migrations_dir = "migrations"
